# Generated by Django 2.2.4 on 2019-09-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_raportowanie', '0003_auto_20190910_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='change',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='change',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='status',
            field=models.CharField(choices=[('nowy', 'nowy'), ('w obserwacji', 'w obserwacji'), ('wstrzymane', 'wstrzymane'), ('przekazane', 'przekazane'), ('w realizacji', 'w realizacji'), ('zamknięte', 'zamknięte')], default='nowy', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('nowy', 'nowy'), ('w obserwacji', 'w obserwacji'), ('wstrzymane', 'wstrzymane'), ('przekazane', 'przekazane'), ('w realizacji', 'w realizacji'), ('zamknięte', 'zamknięte')], default='nowy', max_length=15),
        ),
    ]
