# Generated by Django 2.2.4 on 2019-09-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_raportowanie', '0005_auto_20190911_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
