# Generated by Django 2.2.4 on 2019-09-19 14:38

import aplikacja_raportowanie.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_raportowanie', '0008_auto_20190918_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[aplikacja_raportowanie.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[aplikacja_raportowanie.validators.validate_file_size]),
        ),
    ]
