# Generated by Django 2.2.4 on 2019-09-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_raportowanie', '0012_auto_20190923_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='tictet_number',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tictet_number',
        ),
    ]
