# Generated by Django 2.2.4 on 2019-09-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_raportowanie', '0015_auto_20190924_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='long_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='long_term',
            field=models.BooleanField(default=False),
        ),
    ]
