# Generated by Django 2.2.4 on 2019-09-24 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_raportowanie', '0016_auto_20190924_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_article_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
